name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Keep using Ruby 2.7

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: |
        bundle install
        bundle exec pod install --repo-update
      working-directory: ios

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1'

    - name: Build iOS app
      run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator -configuration Release build
      env:
        CI: true