name: Build iOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'  # Update to a compatible version

    - name: Install compatible securerandom
      run: gem install securerandom -v 0.3.2

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install --repo-update
      working-directory: ios

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2.1'

    - name: Build iOS app
      run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator -configuration Release build
      env:
        CI: true